My first Microverse mobile project
bohaz/First-mobile-project pull request #1
Opened 2023-04-29 08:26 UTC by bohaz

Features Added
-Linters configuration
-Git ignore
-Html and CSS files
-Readme file

2023-04-29 09:09 UTC, tufoinnkuo10 requested changes
Hi @bohaz 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally


Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/PO5SrPjY1EBSDvILb2/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-04-29 09:09 UTC, tufoinnkuo10 commented on README.md
> +
- [optional] please always rename your project in the README to reflect what you are currently working on. you can rename this title like you did up.

2023-04-29 09:09 UTC, tufoinnkuo10 commented on index.html
> +      </button>
- [ ] please kindly ensure The hamburger button is on the right, and has a `nav` tag.

* The `nav` tag is for semantics reason, and the right position for convention and user experience for mobile devices.
* kindly remove the button tag from the hamburger icon
![Screenshot (1021)_LI](https://user-images.githubusercontent.com/65298048/235293868-7778c6e5-48b2-4394-a7b5-058aebaf3948.jpg)

2023-04-29 09:09 UTC, tufoinnkuo10 commented on index.html
> +          <img src="img/Social Media.png" alt="social"/>
- [ ] Great job with the social icons. unfortunately its not an image but they a different social icons which are aimed at linking the viewer to your different social profiles. please the list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag).

* Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.

2023-04-29 09:09 UTC, tufoinnkuo10 commented on style.css
> +  width: 422px;
- [ ] please set this width to 100% so as to make it responsive, also justify-content: space-between

2023-04-29 09:09 UTC, tufoinnkuo10 commented on style.css
> +  width: 375px;
- [ ] Remember you work should be responsive up to the desktop version (768px) kindly set the width here to 100% as well to make the section responsive, ensure the background image is well positioned after making the change
![Screenshot (1022)_LI](https://user-images.githubusercontent.com/65298048/235294531-416b9647-5783-4797-b497-8fa0c71fc160.jpg)

2023-04-30 04:04 UTC, stanleySimeon requested changes
# Hi @maths29 
 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media2.giphy.com/media/vQGBDTkhtIunaJYmRF/giphy-downsized.gif?cid=29caca75sf3uq9y4qgulk5ybbojwg94b4zo6temfzeel417x&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g
)

## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Good PR description ✔️
- Meaningful commit messages ✔️

# Required Changes ♻️

* [ ] Kindly I suggest you follow the Figma design to make your project look more professional. Check this [link](templates in Figma) to follow the Figma template.

> ### The Figma design
>
><img width="336" alt="Screenshot 2023-04-30 at 00 02 39" src="https://user-images.githubusercontent.com/91237525/235334930-c3f2bac7-e75f-4581-b743-b255290fa0e0.png">
>
> ### Your design
>
><img width="377" alt="Screenshot 2023-04-30 at 00 03 18" src="https://user-images.githubusercontent.com/91237525/235334950-bc566867-0c19-4acc-bb14-c2ce1127db99.png">


- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers, and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @stanleySimeon in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 19:45 UTC, Ibizugbe reviewed
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

I can see you are repeating the week and you are using the same PR from last week for same milestone, Kindly checkout to a new branch and ensure all the requirements for the milestone are met. open a PR fro the new branch and submit for review👍.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-01 21:32 UTC, bohaz commented
Hi i have created a new pull request for this new week

2023-05-04 01:23 UTC, merged